[package]
name = "ec"
version = "0.1.5"
edition = "2021"
description = "A systems level compiler for EC (sentence based code)"

[dependencies]
thiserror = "2.0"

[profile.release]
opt-level = 3
lto = true
